### PR TITLE
add support on symfony/yaml 3.x branch

### PR DESCRIPTION
**Pull request by elernonelma**

### CODE REVIEW

**Comment by nackjicholson** [comment]
@elernonelma I have not written PHP in a few years would you like to own this project?

**Comment by nackjicholson** [comment]
I don't even have composer on my current computer. Don't really even remember how to ship this to packagist.

**Comment by elernonelma** [comment]
Thanks for the merge and your proposition. Feel free to give me the rights; if you really don't plan to spend more time on this, should be fine to me.

**Comment by elernonelma** [comment]
thx @nackjicholson !

**Comment by nackjicholson** [comment]
I tried to add you as a maintainer on pacakagist.com, so let me know if you need anything more.

Cheers mate! Thank you very much for taking this on.

Update: oh, actually I don't have your packagist username, it erred, so let me know what your name is on there so I can add you as a maintainer.

**Comment by elernonelma** [comment]
You're welcome ;) I was not registered on packagist yet. It's solved, my username is elernonelma :)

**Comment by nackjicholson** [comment]
@elernonelma You've been added! Thanks again for the help, and let me know if I need to do anything else to empower you to make changes :)

**Pull request merged**
